<#
  Atithi — one-click deploy (Windows / PowerShell).

  Prereqs (do these ONCE on a new machine/account):
    1. aws configure         # set access key, secret, and a default region
    2. git clone <repo> && cd Atithi-resort-project
    3. .\deploy.ps1

  Everything else is automatic: installs deps, builds all workspaces, bootstraps
  CDK if needed, deploys the platform stack, wires the frontend to the live API,
  builds + deploys the web stack, and prints the CloudFront URL.

  Optional overrides:
    .\deploy.ps1 -Stage dev -Region ap-south-1
#>
[CmdletBinding()]
param(
  [string]$Stage  = $(if ($env:STAGE) { $env:STAGE } else { "dev" }),
  # Canonical region for Atithi (India data residency, per docs/11). Override with
  # -Region or $env:AWS_REGION. We do NOT inherit the CLI default region, so the
  # deploy lands in the same place on every machine regardless of local config.
  [string]$Region = $(if ($env:AWS_REGION) { $env:AWS_REGION } elseif ($env:AWS_DEFAULT_REGION) { $env:AWS_DEFAULT_REGION } else { "ap-south-1" })
)

$ErrorActionPreference = "Stop"
$root = $PSScriptRoot
Set-Location $root

if (-not $Region) { $Region = "ap-south-1" }

Write-Host "==> Atithi deploy | stage=$Stage region=$Region" -ForegroundColor Cyan

# --- Verify prerequisites -------------------------------------------------
foreach ($tool in @("node","npm","aws")) {
  if (-not (Get-Command $tool -ErrorAction SilentlyContinue)) {
    throw "'$tool' not found on PATH. Install it (and run 'aws configure') before deploying."
  }
}

$identity = aws sts get-caller-identity --output json | ConvertFrom-Json
if (-not $identity.Account) { throw "AWS credentials not configured. Run 'aws configure' first." }
$Account = $identity.Account
Write-Host "==> AWS account: $Account" -ForegroundColor Cyan

# CDK resolves the deploy region from the CLI region (AWS_REGION / AWS_DEFAULT_REGION),
# NOT from CDK_DEFAULT_REGION. Pin all of them so the deploy is deterministic.
$env:AWS_REGION         = $Region
$env:AWS_DEFAULT_REGION = $Region
$env:CDK_DEFAULT_ACCOUNT = $Account
$env:CDK_DEFAULT_REGION  = $Region
$env:STAGE               = $Stage

$cdk = "npx cdk"

# --- 1. Install + build ---------------------------------------------------
Write-Host "==> Installing dependencies..." -ForegroundColor Cyan
npm install

Write-Host "==> Building shared, backend, infrastructure..." -ForegroundColor Cyan
npm run build -w packages/shared
npm run build -w backend
npm run build -w infrastructure

# --- 2. Bootstrap CDK if this account/region has never been bootstrapped ---
$bootstrapped = $true
try {
  aws cloudformation describe-stacks --stack-name CDKToolkit --region $Region --output json 2>$null | Out-Null
  if ($LASTEXITCODE -ne 0) { $bootstrapped = $false }
} catch { $bootstrapped = $false }

if (-not $bootstrapped) {
  Write-Host "==> Bootstrapping CDK (first time on this account/region)..." -ForegroundColor Cyan
  Push-Location infrastructure
  Invoke-Expression "$cdk bootstrap aws://$Account/$Region"
  Pop-Location
} else {
  Write-Host "==> CDK already bootstrapped." -ForegroundColor DarkGray
}

# --- 3. Deploy the platform stack (DynamoDB, Cognito, Lambda, API) ---------
Write-Host "==> Deploying AtithiPlatform-$Stage ..." -ForegroundColor Cyan
Push-Location infrastructure
Invoke-Expression "$cdk deploy AtithiPlatform-$Stage --require-approval never --outputs-file platform-outputs.json"
$platform = (Get-Content platform-outputs.json -Raw | ConvertFrom-Json)."AtithiPlatform-$Stage"
Pop-Location

if (-not $platform.ApiUrl) { throw "Platform deploy produced no ApiUrl output." }

# --- 4. Wire the frontend to the live API + Cognito, then build -----------
Write-Host "==> Writing frontend/.env.production from live outputs..." -ForegroundColor Cyan
@"
# Generated by deploy.ps1 from AtithiPlatform-$Stage CDK outputs. Do not hand-edit.
VITE_API_BASE_URL=$($platform.ApiUrl)
VITE_USER_POOL_ID=$($platform.UserPoolId)
VITE_USER_POOL_CLIENT_ID=$($platform.UserPoolClientId)
VITE_AWS_REGION=$Region
VITE_DEFAULT_LOCALE=en
"@ | Set-Content -Path "frontend/.env.production" -Encoding utf8

Write-Host "==> Building frontend..." -ForegroundColor Cyan
npm run build -w frontend

# --- 5. Deploy the web stack (S3 + CloudFront) ----------------------------
Write-Host "==> Deploying AtithiWeb-$Stage (S3 + CloudFront)..." -ForegroundColor Cyan
Push-Location infrastructure
Invoke-Expression "$cdk deploy AtithiWeb-$Stage --require-approval never --outputs-file web-outputs.json"
$web = (Get-Content web-outputs.json -Raw | ConvertFrom-Json)."AtithiWeb-$Stage"
Pop-Location

if (-not $web.WebUrl) { throw "Web deploy produced no WebUrl output." }

# --- 6. Done --------------------------------------------------------------
Write-Host ""
Write-Host "============================================================" -ForegroundColor Green
Write-Host " Atithi is live" -ForegroundColor Green
Write-Host "   CloudFront URL : $($web.WebUrl)" -ForegroundColor Green
Write-Host "   API URL        : $($platform.ApiUrl)" -ForegroundColor Green
Write-Host "   Distribution   : $($web.DistributionId)" -ForegroundColor Green
Write-Host "============================================================" -ForegroundColor Green
