#!/usr/bin/env bash
#
# Atithi — one-click deploy (Linux / macOS / Git-Bash / WSL).
#
# Prereqs (do these ONCE on a new machine/account):
#   1. aws configure          # set access key, secret, and a default region
#   2. git clone <repo> && cd Atithi-resort-project
#   3. ./deploy.sh
#
# Everything else is automatic: installs deps, builds all workspaces, bootstraps
# CDK if needed, deploys the platform stack, wires the frontend to the live API,
# builds + deploys the web stack, and prints the CloudFront URL.
#
# Optional overrides:  STAGE=dev AWS_REGION=ap-south-1 ./deploy.sh
#
set -euo pipefail

cd "$(dirname "$0")"

STAGE="${STAGE:-dev}"
# Canonical region for Atithi (India data residency, per docs/11). Override with
# AWS_REGION=... We do NOT inherit the CLI default region, so the deploy lands in
# the same place on every machine regardless of local config.
REGION="${AWS_REGION:-${AWS_DEFAULT_REGION:-ap-south-1}}"

echo "==> Atithi deploy | stage=$STAGE region=$REGION"

# --- Verify prerequisites -------------------------------------------------
for tool in node npm aws; do
  command -v "$tool" >/dev/null 2>&1 || { echo "ERROR: '$tool' not found on PATH. Install it (and run 'aws configure') first."; exit 1; }
done

ACCOUNT="$(aws sts get-caller-identity --query Account --output text)"
[ -n "$ACCOUNT" ] || { echo "ERROR: AWS credentials not configured. Run 'aws configure'."; exit 1; }
echo "==> AWS account: $ACCOUNT"

# CDK resolves the deploy region from the CLI region (AWS_REGION / AWS_DEFAULT_REGION),
# NOT from CDK_DEFAULT_REGION. Pin all of them so the deploy is deterministic.
export AWS_REGION="$REGION"
export AWS_DEFAULT_REGION="$REGION"
export CDK_DEFAULT_ACCOUNT="$ACCOUNT"
export CDK_DEFAULT_REGION="$REGION"
export STAGE

# --- AI provider: Kimi (Moonshot) by default -----------------------------
# Kimi is OpenAI-compatible. The key is read from Secrets Manager at runtime,
# never baked into code. Use the fast 'highspeed' model — the k2.6/k3 reasoning
# models take 30s+ per call and blow past API Gateway's 29s ceiling.
# Override any of these by exporting the env var before running the script.
export AI_PROVIDER="${AI_PROVIDER:-openai}"
export OPENAI_BASE_URL="${OPENAI_BASE_URL:-https://api.moonshot.ai/v1}"
export OPENAI_MODEL="${OPENAI_MODEL:-kimi-k2.7-code-highspeed}"
AI_SECRET_ID="${AI_API_KEY_SECRET_ID:-atithi/$STAGE/ai-api-key}"

# Only wire the AI key if the secret actually exists — otherwise fall back to
# Bedrock so the deploy still succeeds on an account without a Kimi key.
if aws secretsmanager describe-secret --secret-id "$AI_SECRET_ID" --region "$REGION" >/dev/null 2>&1; then
  export AI_API_KEY_SECRET_ID="$AI_SECRET_ID"
  echo "==> AI: Kimi via $OPENAI_MODEL (secret '$AI_SECRET_ID')"
else
  echo "==> AI key secret '$AI_SECRET_ID' not found — falling back to Bedrock."
  echo "    To use Kimi: aws secretsmanager create-secret --name $AI_SECRET_ID --secret-string '{\"apiKey\":\"sk-...\"}' --region $REGION"
  export AI_PROVIDER="bedrock"
  export AI_API_KEY_SECRET_ID=""
fi

CDK="npx cdk"

# --- 1. Install + build ---------------------------------------------------
echo "==> Installing dependencies..."
npm install

echo "==> Building shared, backend, infrastructure..."
npm run build -w packages/shared
npm run build -w backend
npm run build -w infrastructure

# --- 2. Bootstrap CDK if this account/region has never been bootstrapped ---
if ! aws cloudformation describe-stacks --stack-name CDKToolkit --region "$REGION" >/dev/null 2>&1; then
  echo "==> Bootstrapping CDK (first time on this account/region)..."
  ( cd infrastructure && $CDK bootstrap "aws://$ACCOUNT/$REGION" )
else
  echo "==> CDK already bootstrapped."
fi

# --- 3. Deploy the platform stack (DynamoDB, Cognito, Lambda, API) ---------
echo "==> Deploying AtithiPlatform-$STAGE ..."
( cd infrastructure && $CDK deploy "AtithiPlatform-$STAGE" --require-approval never --outputs-file platform-outputs.json )

read_out() { # read_out <file> <stack> <key>
  node -e "const o=require('./$1')['$2'];process.stdout.write(o['$3']||'')"
}

API_URL="$(read_out infrastructure/platform-outputs.json "AtithiPlatform-$STAGE" ApiUrl)"
POOL_ID="$(read_out infrastructure/platform-outputs.json "AtithiPlatform-$STAGE" UserPoolId)"
CLIENT_ID="$(read_out infrastructure/platform-outputs.json "AtithiPlatform-$STAGE" UserPoolClientId)"
[ -n "$API_URL" ] || { echo "ERROR: platform deploy produced no ApiUrl."; exit 1; }

# --- 4. Wire the frontend to the live API + Cognito, then build -----------
echo "==> Writing frontend/.env.production from live outputs..."
cat > frontend/.env.production <<EOF
# Generated by deploy.sh from AtithiPlatform-$STAGE CDK outputs. Do not hand-edit.
VITE_API_BASE_URL=$API_URL
VITE_USER_POOL_ID=$POOL_ID
VITE_USER_POOL_CLIENT_ID=$CLIENT_ID
VITE_AWS_REGION=$REGION
VITE_DEFAULT_LOCALE=en
EOF

echo "==> Building frontend..."
npm run build -w frontend

# --- 5. Deploy the web stack (S3 + CloudFront) ----------------------------
echo "==> Deploying AtithiWeb-$STAGE (S3 + CloudFront)..."
( cd infrastructure && $CDK deploy "AtithiWeb-$STAGE" --require-approval never --outputs-file web-outputs.json )

WEB_URL="$(read_out infrastructure/web-outputs.json "AtithiWeb-$STAGE" WebUrl)"
DIST_ID="$(read_out infrastructure/web-outputs.json "AtithiWeb-$STAGE" DistributionId)"
[ -n "$WEB_URL" ] || { echo "ERROR: web deploy produced no WebUrl."; exit 1; }

# --- 6. Done --------------------------------------------------------------
echo ""
echo "============================================================"
echo " Atithi is live"
echo "   CloudFront URL : $WEB_URL"
echo "   API URL        : $API_URL"
echo "   Distribution   : $DIST_ID"
echo "============================================================"
